from __future__ import annotations
"""Shared templates used by file I/O export helpers."""

__docformat__ = "google"

_x3d_html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> vedo with x3d </title>

  <!-- THESE ARE THE RELEVANT LINES: -->
  <script src='https://www.x3dom.org/download/x3dom.js'> </script>
  <link rel='stylesheet' type='text/css' href='https://www.x3dom.org/download/x3dom.css'/>

  <style>
     table, td, th { border: 1px solid black; background-color: powderblue;}
     table {width: 70%; border-collapse: collapse;}
     table th {width: 35%;}
  </style>
</head>

<body style="font-family: Verdana">
  <h1>Example html generated by vedo</h1>
  This example loads a 3D scene from file ~fileoutput generated by
  <a href="https://github.com/marcomusy/vedo">vedo</a>
  (see <a href="https://github.com/marcomusy/vedo/tree/master/examples/other/export_x3d.py">export_x3d.py</a>).
  <br><br>


  <!-- THESE ARE THE RELEVANT LINES: -->
  <x3d width='~widthpx' height='~heightpx'>
     <scene>
        <Inline url="~fileoutput"> </Inline>
     </scene>
  </x3d>

  <h3>Nothing shows up above this line?</h3>
  Enable your browser to load local files:
  <br><b>Firefox</b>: type <code>about:config</code> in the URL bar and
  change <code>privacy.file_unique_origin</code> from <code>True</code> to <code>False</code>
  <br><b>Chrome</b>: from terminal type:
  <code>google-chrome --enable-webgl --allow-file-access-from-files</code>
  (see <a href="https://cmatskas.com/interacting-with-local-data-files-using-chrome/">here</a>)

  <br>
  <h3>Controls:</h3>
  <h4><strong>Examine Mode (activate with key 'e'):</strong></h4>
  <table>
     <tbody>
        <tr class="even description">
           <th>Button</th>
           <th>Function</th>
        </tr>
        <tr>
           <td>Left Button / Left Button + Shift</td>
           <td>Rotate</td>
        </tr>
        <tr>
           <td>Mid Button / Left Button + Ctl</td>
           <td>Pan</td>
        </tr>
        <tr>
           <td>Right Button / Wheel / Left Button + Alt</td>
           <td>Zoom</td>
        </tr>
        <tr>
           <td>Left double click</td>
           <td>Set center of rotation</td>
        </tr>
     </tbody>
  </table>
  <h4><strong>Walk Mode (activate with key 'w'):</strong></h4>
  <table>
     <tbody>
        <tr class="even description">
           <th>Button</th>
           <th>Function</th>
        </tr>
        <tr>
           <td>Left Button</td>
           <td>Move forward</td>
        </tr>
        <tr>
           <td>Right Button</td>
           <td>Move backward</td>
        </tr>
     </tbody>
  </table>
  <h4><strong>Fly Mode (activate with key 'f'):</strong></h4>
  <table>
     <tbody>
        <tr class="even description">
           <th>Button</th>
           <th>Function</th>
        </tr>
        <tr>
           <td>Left Button</td>
           <td>Move forward</td>
        </tr>
        <tr>
           <td>Right Button</td>
           <td>Move backward</td>
        </tr>
     </tbody>
  </table>
  <h3>Non-interactive camera movement</h3>
  <table>
     <tbody>
        <tr class="even description">
           <th>Key</th>
           <th>Function</th>
        </tr>
        <tr>
           <td>r</td>
           <td>reset view</td>
        </tr>
        <tr>
           <td>a</td>
           <td>show all</td>
        </tr>
        <tr>
           <td>u</td>
           <td>upright</td>
        </tr>
     </tbody>
  </table>
</body>
</html>
"""


_threejs_html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>~title</title>
  <style>
    :root {
      color-scheme: light dark;
      --panel-bg: rgba(15, 23, 42, 0.72);
      --panel-border: rgba(255, 255, 255, 0.16);
      --panel-text: #e5eefb;
      --panel-muted: #b8c6dc;
    }
    html, body {
      margin: 0;
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: ~background;
      font-family: Verdana, sans-serif;
    }
    #viewer {
      width: 100%;
      height: 100%;
    }
    #overlay {
      position: fixed;
      top: 16px;
      left: 16px;
      max-width: min(420px, calc(100vw - 32px));
      padding: 12px 14px;
      border-radius: 12px;
      background: var(--panel-bg);
      border: 1px solid var(--panel-border);
      color: var(--panel-text);
      backdrop-filter: blur(10px);
      box-shadow: 0 12px 30px rgba(0, 0, 0, 0.18);
      pointer-events: none;
    }
    #overlay h1 {
      margin: 0 0 6px 0;
      font-size: 16px;
      line-height: 1.25;
    }
    #overlay p {
      margin: 0;
      font-size: 12px;
      line-height: 1.5;
      color: var(--panel-muted);
    }
    #unsupported {
      margin-top: 10px;
      font-size: 12px;
      line-height: 1.45;
      color: #ffd6a5;
      white-space: pre-wrap;
    }
    .label-2d {
      position: fixed;
      transform: translate(-50%, -50%);
      padding: 2px 8px;
      border-radius: 999px;
      font-size: 12px;
      pointer-events: none;
      white-space: nowrap;
    }
  </style>
  <script type="importmap">
    {
      "imports": {
        "three": "https://unpkg.com/three@0.167.1/build/three.module.js",
        "three/addons/": "https://unpkg.com/three@0.167.1/examples/jsm/"
      }
    }
  </script>
</head>
<body>
  <div id="viewer"></div>
  <div id="overlay">
    <h1>~title</h1>
    <p>Generated by <a href="https://github.com/marcomusy/vedo" target="_blank" rel="noreferrer" style="color:#c7defe; pointer-events:auto;">vedo</a>. Drag to orbit, scroll to zoom, right-drag to pan.</p>
    <div id="unsupported"></div>
  </div>
  <script id="vedo-scene-data" type="application/json">~scene_data</script>
  <script type="module">
    import * as THREE from "three";
    import { OrbitControls } from "three/addons/controls/OrbitControls.js";

    const payload = JSON.parse(document.getElementById("vedo-scene-data").textContent);
    const container = document.getElementById("viewer");
    const unsupportedEl = document.getElementById("unsupported");
    const tuning = payload.threejs || {};

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(window.devicePixelRatio || 1);
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    container.appendChild(renderer.domElement);

    const scene = new THREE.Scene();
    if (payload.background.primary && !payload.background.secondary) {
      scene.background = new THREE.Color(payload.background.primary);
    }

    const aspect = window.innerWidth / Math.max(window.innerHeight, 1);
    let camera;
    if (payload.camera.parallel_projection) {
      const scale = payload.camera.parallel_scale || 1;
      camera = new THREE.OrthographicCamera(
        -scale * aspect,
        scale * aspect,
        scale,
        -scale,
        0.01,
        1e7
      );
    } else {
      camera = new THREE.PerspectiveCamera(30, aspect, 0.01, 1e7);
    }

    const camPos = payload.camera.position || [1, 1, 1];
    const camTarget = payload.camera.focal_point || [0, 0, 0];
    const camUp = payload.camera.viewup || [0, 0, 1];
    camera.position.set(...camPos);
    camera.up.set(...camUp);
    camera.lookAt(...camTarget);

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.target.set(...camTarget);
    controls.update();

    scene.add(camera);
    // VTK's default automatic-light setup is close to a single headlight
    // aimed from the camera toward the focal point.
    const headLight = new THREE.DirectionalLight(0xffffff, tuning.headlight_intensity ?? 1.0);
    headLight.position.set(0, 0, 1);
    camera.add(headLight);
    camera.add(headLight.target);

    if (payload.helpers.show_axes) {
      scene.add(new THREE.AxesHelper(payload.helpers.axes_size || 1));
    }
    if (payload.helpers.show_grid) {
      const size = payload.helpers.grid_size || 1;
      const divisions = payload.helpers.grid_divisions || 10;
      const grid = new THREE.GridHelper(size, divisions, 0x8090a0, 0x506070);
      grid.rotateX(Math.PI / 2);
      scene.add(grid);
    }

    function applyMatrix(object, matrixRows) {
      if (!matrixRows) return;
      const flat = matrixRows.flat();
      if (flat.length !== 16) return;
      object.matrixAutoUpdate = false;
      object.matrix.set(...flat);
    }

    const TYPE_ARRAYS = {
      float32: Float32Array,
      uint8: Uint8Array,
      uint16: Uint16Array,
      uint32: Uint32Array,
      int32: Int32Array,
    };

    function decodePackedArray(value) {
      if (!value || value.encoding !== "base64" || typeof value.data !== "string") {
        return null;
      }
      const TypeCtor = TYPE_ARRAYS[value.dtype];
      if (!TypeCtor) {
        console.warn("Unsupported packed array dtype:", value.dtype);
        return null;
      }
      const binary = atob(value.data);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i) & 0xff;
      }
      const bytesPerElement = TypeCtor.BYTES_PER_ELEMENT;
      const expectedLength = Number.isInteger(value.length) ? value.length : Math.floor(bytes.length / bytesPerElement);
      const expectedBytes = expectedLength * bytesPerElement;
      if (expectedBytes > bytes.byteLength || expectedBytes % bytesPerElement !== 0) {
        console.warn("Packed array size mismatch:", value);
        return null;
      }
      return new TypeCtor(bytes.buffer, bytes.byteOffset, expectedLength);
    }

    function unpackArray(value) {
      if (value == null) return null;
      if (Array.isArray(value) || ArrayBuffer.isView(value)) {
        return value;
      }
      return decodePackedArray(value);
    }

    function toFloat32Array(value) {
      const unpacked = unpackArray(value);
      if (unpacked == null) return null;
      if (unpacked instanceof Float32Array) return unpacked;
      if (Array.isArray(unpacked) || ArrayBuffer.isView(unpacked)) {
        return new Float32Array(unpacked);
      }
      return null;
    }

    function toUint8Array(value) {
      const unpacked = unpackArray(value);
      if (unpacked == null) return null;
      if (unpacked instanceof Uint8Array || unpacked instanceof Uint8ClampedArray) {
        return unpacked;
      }
      if (Array.isArray(unpacked) || ArrayBuffer.isView(unpacked)) {
        return new Uint8Array(unpacked);
      }
      return null;
    }

    function toIndexArray(value) {
      const unpacked = unpackArray(value);
      if (unpacked == null) return null;
      if (
        unpacked instanceof Uint16Array ||
        unpacked instanceof Uint32Array ||
        unpacked instanceof Int32Array
      ) {
        return unpacked;
      }
      if (!Array.isArray(unpacked) && !ArrayBuffer.isView(unpacked)) {
        return null;
      }
      const arrayValues = Array.from(unpacked);
      if (!arrayValues.length) return null;
      let maxValue = 0;
      for (const v of arrayValues) {
        if (v > maxValue) maxValue = v;
      }
      return maxValue < 65536 ? new Uint16Array(arrayValues) : new Uint32Array(arrayValues);
    }

    function safeBufferAttribute(array, itemSize, label) {
      if (!array || typeof array.length !== "number" || array.length === 0) {
        console.warn("Skipping invalid attribute:", label, array);
        return null;
      }
      try {
        return new THREE.BufferAttribute(array, itemSize);
      } catch (error) {
        console.warn("Failed to build attribute:", label, error, array);
        return null;
      }
    }

    function rgbArrayToAttribute(values, itemSize = 3) {
      const array = toFloat32Array(values);
      if (!array || !array.length) return null;
      return safeBufferAttribute(array, itemSize, "color");
    }

    function buildGeometry(object) {
      const geometry = new THREE.BufferGeometry();
      const positions = toFloat32Array(object.positions);
      if (!positions || !positions.length) {
        return null;
      }
      const positionAttr = safeBufferAttribute(positions, 3, `${object.name || object.kind}:position`);
      if (!positionAttr) {
        return null;
      }
      geometry.setAttribute("position", positionAttr);
      const normals = toFloat32Array(object.normals);
      const hasNormals = normals && normals.length === positions.length;
      if (hasNormals) {
        const normalAttr = safeBufferAttribute(normals, 3, `${object.name || object.kind}:normal`);
        if (normalAttr) {
          geometry.setAttribute("normal", normalAttr);
        }
      }
      const uvs = toFloat32Array(object.uvs);
      if (uvs && uvs.length) {
        const uvAttr = safeBufferAttribute(uvs, 2, `${object.name || object.kind}:uv`);
        if (uvAttr) {
          geometry.setAttribute("uv", uvAttr);
        }
      }
      const vertexColors = unpackArray(object.vertex_colors);
      if (vertexColors && vertexColors.length) {
        const colorAttr = rgbArrayToAttribute(vertexColors);
        if (colorAttr) {
          geometry.setAttribute("color", colorAttr);
        }
      }
      const indices = toIndexArray(object.indices);
      if (indices && indices.length) {
        const indexAttr = safeBufferAttribute(indices, 1, `${object.name || object.kind}:index`);
        if (indexAttr) {
          geometry.setIndex(indexAttr);
        }
      }
      if (object.kind === "mesh" && !geometry.getAttribute("normal")) {
        geometry.computeVertexNormals();
      }
      geometry.computeBoundingSphere();
      return geometry;
    }

    function buildTexture(textureData) {
      if (!textureData || !textureData.data) {
        return null;
      }
      const src = toUint8Array(textureData.data);
      if (!src || !src.length) {
        return null;
      }
      const srcClamped = src instanceof Uint8ClampedArray ? src : new Uint8ClampedArray(src);
      const rgba = new Uint8ClampedArray(textureData.width * textureData.height * 4);
      if (textureData.channels === 4) {
        rgba.set(srcClamped);
      } else {
        for (let i = 0, j = 0; i < srcClamped.length; i += 3, j += 4) {
          rgba[j] = srcClamped[i];
          rgba[j + 1] = srcClamped[i + 1];
          rgba[j + 2] = srcClamped[i + 2];
          rgba[j + 3] = 255;
        }
      }
      const canvas = document.createElement("canvas");
      canvas.width = textureData.width;
      canvas.height = textureData.height;
      const ctx = canvas.getContext("2d");
      const imageData = new ImageData(rgba, textureData.width, textureData.height);
      ctx.putImageData(imageData, 0, 0);
      const texture = new THREE.CanvasTexture(canvas);
      texture.colorSpace = THREE.SRGBColorSpace;
      texture.flipY = true;
      texture.generateMipmaps = false;
      texture.wrapS = textureData.repeat ? THREE.RepeatWrapping : THREE.ClampToEdgeWrapping;
      texture.wrapT = textureData.repeat ? THREE.RepeatWrapping : THREE.ClampToEdgeWrapping;
      texture.magFilter = textureData.interpolate ? THREE.LinearFilter : THREE.NearestFilter;
      texture.minFilter = textureData.interpolate ? THREE.LinearFilter : THREE.NearestFilter;
      texture.needsUpdate = true;
      return texture;
    }

    function buildEdgeLines(object) {
      const edgeSegments = toFloat32Array(object.edge_segments);
      if (!edgeSegments || !edgeSegments.length) {
        return null;
      }
      const edgeGeometry = new THREE.BufferGeometry();
      const edgeAttr = safeBufferAttribute(edgeSegments, 3, `${object.name || object.kind}:edges`);
      if (!edgeAttr) {
        return null;
      }
      edgeGeometry.setAttribute(
        "position",
        edgeAttr
      );
      const edgeMaterial = new THREE.LineBasicMaterial({
        color: object.edge_color || object.color || "#d9dde3",
        transparent: object.opacity < 0.999,
        opacity: object.opacity,
      });
      return new THREE.LineSegments(edgeGeometry, edgeMaterial);
    }

    function makeLabel(object) {
      const el = document.createElement("div");
      el.className = "label-2d";
      el.textContent = object.text;
      el.style.left = `${object.position[0] * 100}%`;
      el.style.top = `${(1 - object.position[1]) * 100}%`;
      el.style.color = object.color || "#ffffff";
      el.style.fontSize = `${Math.max(11, object.size * 14)}px`;
      if (object.frame) {
        el.style.border = "1px solid rgba(255,255,255,0.25)";
      }
      if (object.background) {
        el.style.background = object.background;
      }
      container.appendChild(el);
    }

    const bounds = new THREE.Box3();
    let hasRenderableObjects = false;

    for (const object of payload.objects) {
      if (object.kind === "text2d") {
        makeLabel(object);
        continue;
      }

      if (object.kind === "mesh") {
        const geometry = buildGeometry(object);
        if (!geometry) {
          console.warn("Skipping mesh with invalid geometry:", object.name || object.kind);
          continue;
        }
        const texture = buildTexture(object.texture);
        const baseColor = new THREE.Color(texture ? "#ffffff" : (object.color || "#d9dde3"));
        const exportedSpecular = typeof object.specular === "number" ? object.specular : 0;
        const useSpecularFallback =
          Boolean(object.lighting) &&
          !Boolean(object.flat_shading) &&
          exportedSpecular <= 1e-6;
        const ambientStrength =
          !object.lighting ? 1.0 : ((object.ambient || 0) * (tuning.ambient_scale ?? 0.25));
        const emissive = baseColor.clone().multiplyScalar(ambientStrength);
        const specularStrength = useSpecularFallback
          ? (tuning.fallback_specular_strength ?? 0.35)
          : (exportedSpecular * (tuning.specular_scale ?? 0.45));
        const specularColor = new THREE.Color(object.specular_color || "#111111");
        if (useSpecularFallback) {
          // VTK's default shaded look still reads slightly glossy even when the
          // raw property exports as specular=0. Add a small highlight so smooth
          // surfaces like the bunny do not become unnaturally matte in Three.js.
          specularColor.lerp(new THREE.Color("#ffffff"), 0.5);
        }
        const shininess =
          exportedSpecular > 1e-6
            ? Math.max(1, object.specular_power || 1)
            : (useSpecularFallback
              ? Math.max(1, tuning.fallback_shininess ?? 28)
              : Math.max(1, object.specular_power || 1));
        const material = new THREE.MeshPhongMaterial({
          color: baseColor,
          side: THREE.DoubleSide,
          transparent: object.opacity < 0.999,
          opacity: object.opacity,
          wireframe: false,
          flatShading: Boolean(object.flat_shading),
          vertexColors: Boolean(object.vertex_colors && object.vertex_colors.length),
          map: texture,
          emissive,
          specular: specularColor.multiplyScalar(specularStrength),
          shininess,
          polygonOffset: Boolean(object.edge_visibility),
          polygonOffsetFactor: 1,
          polygonOffsetUnits: 1,
        });
        material.toneMapped = false;
        if (!object.lighting) {
          material.emissive.copy(baseColor);
        } else if (
          !Boolean(tuning.preserve_base_color) &&
          typeof object.diffuse === "number" &&
          object.diffuse < 0.999
        ) {
          material.color.multiplyScalar(object.diffuse);
        }
        const mesh = new THREE.Mesh(geometry, material);
        const group = new THREE.Group();
        if (!object.wireframe) {
          group.add(mesh);
        }
        const edges = buildEdgeLines(object);
        if (edges && (object.wireframe || object.edge_visibility)) {
          group.add(edges);
        }
        scene.add(group);
        bounds.expandByObject(group);
        hasRenderableObjects = true;
        continue;
      }

      if (object.kind === "points") {
        const geometry = buildGeometry(object);
        if (!geometry) {
          console.warn("Skipping points with invalid geometry:", object.name || object.kind);
          continue;
        }
        const material = new THREE.PointsMaterial({
          color: object.color || "#d9dde3",
          size: object.point_size || 4,
          transparent: object.opacity < 0.999,
          opacity: object.opacity,
          vertexColors: Boolean(object.vertex_colors && object.vertex_colors.length),
          sizeAttenuation: true,
        });
        const points = new THREE.Points(geometry, material);
        applyMatrix(points, object.matrix);
        scene.add(points);
        bounds.expandByObject(points);
        hasRenderableObjects = true;
        continue;
      }

      if (object.kind === "lines") {
        const material = new THREE.LineBasicMaterial({
          color: object.color || "#d9dde3",
          transparent: object.opacity < 0.999,
          opacity: object.opacity,
          vertexColors: Boolean(object.vertex_colors && object.vertex_colors.length),
        });
        const group = new THREE.Group();
        for (const polyline of object.polylines) {
          if (!polyline || polyline.length < 2) continue;
          const lineGeometry = new THREE.BufferGeometry();
          const linePositions = toFloat32Array(polyline);
          const lineAttr = safeBufferAttribute(linePositions, 3, `${object.name || object.kind}:polyline`);
          if (!lineAttr) {
            continue;
          }
          lineGeometry.setAttribute("position", lineAttr);
          const line = new THREE.Line(lineGeometry, material);
          group.add(line);
        }
        applyMatrix(group, object.matrix);
        scene.add(group);
        bounds.expandByObject(group);
        hasRenderableObjects = true;
      }
    }

    if (payload.unsupported.length) {
      unsupportedEl.textContent =
        "Not rendered in this v1 exporter: " +
        payload.unsupported.map((item) => item.label).join(", ");
    }

    if (!hasRenderableObjects) {
      unsupportedEl.textContent =
        (unsupportedEl.textContent ? unsupportedEl.textContent + "\\n" : "") +
        "This scene did not contain any supported Three.js-exportable objects.";
    }

    function updateCamera() {
      const width = window.innerWidth;
      const height = Math.max(window.innerHeight, 1);
      const newAspect = width / height;
      if (camera.isPerspectiveCamera) {
        camera.aspect = newAspect;
      } else {
        const scale = payload.camera.parallel_scale || 1;
        camera.left = -scale * newAspect;
        camera.right = scale * newAspect;
        camera.top = scale;
        camera.bottom = -scale;
      }
      camera.updateProjectionMatrix();
      renderer.setSize(width, height);
    }

    function render() {
      renderer.render(scene, camera);
    }

    window.addEventListener("resize", () => {
      updateCamera();
      render();
    });
    controls.addEventListener("change", render);
    updateCamera();
    render();
  </script>
</body>
</html>
"""


__all__ = ["_x3d_html_template", "_threejs_html_template"]
