from __future__ import annotations

"""Three.js scene export helpers."""

import base64
import json

import numpy as np

from vedo import colors

__docformat__ = "google"

_threejs_html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>~title</title>
  <style>
    :root {
      color-scheme: light dark;
      --panel-bg: rgba(15, 23, 42, 0.72);
      --panel-border: rgba(255, 255, 255, 0.16);
      --panel-text: #e5eefb;
      --panel-muted: #b8c6dc;
    }
    html, body {
      margin: 0;
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: ~background;
      font-family: Verdana, sans-serif;
    }
    #viewer {
      width: 100%;
      height: 100%;
    }
    #overlay {
      position: fixed;
      top: 16px;
      left: 16px;
      max-width: min(420px, calc(100vw - 32px));
      padding: 12px 14px;
      border-radius: 12px;
      background: var(--panel-bg);
      border: 1px solid var(--panel-border);
      color: var(--panel-text);
      backdrop-filter: blur(10px);
      box-shadow: 0 12px 30px rgba(0, 0, 0, 0.18);
      pointer-events: none;
    }
    #overlay h1 {
      margin: 0 0 6px 0;
      font-size: 16px;
      line-height: 1.25;
    }
    #overlay p {
      margin: 0;
      font-size: 12px;
      line-height: 1.5;
      color: var(--panel-muted);
    }
    #unsupported {
      margin-top: 10px;
      font-size: 12px;
      line-height: 1.45;
      color: #ffd6a5;
      white-space: pre-wrap;
    }
    .label-2d {
      position: fixed;
      transform: translate(-50%, -50%);
      padding: 2px 8px;
      border-radius: 999px;
      font-size: 12px;
      pointer-events: none;
      white-space: nowrap;
    }
  </style>
  <script type="importmap">
    {
      "imports": {
        "three": "https://unpkg.com/three@0.167.1/build/three.module.js",
        "three/addons/": "https://unpkg.com/three@0.167.1/examples/jsm/"
      }
    }
  </script>
</head>
<body>
  <div id="viewer"></div>
  <div id="overlay">
    <h1>~title</h1>
    <p>Generated by <a href="https://github.com/marcomusy/vedo" target="_blank" rel="noreferrer" style="color:#c7defe; pointer-events:auto;">vedo</a>. Drag to orbit, scroll to zoom, right-drag to pan.</p>
    <div id="unsupported"></div>
  </div>
  <script id="vedo-scene-data" type="application/json">~scene_data</script>
  <script type="module">
    import * as THREE from "three";
    import { OrbitControls } from "three/addons/controls/OrbitControls.js";

    const payload = JSON.parse(document.getElementById("vedo-scene-data").textContent);
    const container = document.getElementById("viewer");
    const unsupportedEl = document.getElementById("unsupported");
    const tuning = payload.threejs || {};

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(window.devicePixelRatio || 1);
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    container.appendChild(renderer.domElement);

    const scene = new THREE.Scene();
    if (payload.background.primary && !payload.background.secondary) {
      scene.background = new THREE.Color(payload.background.primary);
    }

    const aspect = window.innerWidth / Math.max(window.innerHeight, 1);
    let camera;
    if (payload.camera.parallel_projection) {
      const scale = payload.camera.parallel_scale || 1;
      camera = new THREE.OrthographicCamera(
        -scale * aspect,
        scale * aspect,
        scale,
        -scale,
        0.01,
        1e7
      );
    } else {
      camera = new THREE.PerspectiveCamera(30, aspect, 0.01, 1e7);
    }

    const camPos = payload.camera.position || [1, 1, 1];
    const camTarget = payload.camera.focal_point || [0, 0, 0];
    const camUp = payload.camera.viewup || [0, 0, 1];
    camera.position.set(...camPos);
    camera.up.set(...camUp);
    camera.lookAt(...camTarget);

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.target.set(...camTarget);
    controls.update();

    scene.add(camera);
    // VTK's default automatic-light setup is close to a single headlight
    // aimed from the camera toward the focal point.
    const headLight = new THREE.DirectionalLight(0xffffff, tuning.headlight_intensity ?? 1.0);
    headLight.position.set(0, 0, 1);
    camera.add(headLight);
    camera.add(headLight.target);

    if (payload.helpers.show_axes) {
      scene.add(new THREE.AxesHelper(payload.helpers.axes_size || 1));
    }
    if (payload.helpers.show_grid) {
      const size = payload.helpers.grid_size || 1;
      const divisions = payload.helpers.grid_divisions || 10;
      const grid = new THREE.GridHelper(size, divisions, 0x8090a0, 0x506070);
      grid.rotateX(Math.PI / 2);
      scene.add(grid);
    }

    function applyMatrix(object, matrixRows) {
      if (!matrixRows) return;
      const flat = matrixRows.flat();
      if (flat.length !== 16) return;
      object.matrixAutoUpdate = false;
      object.matrix.set(...flat);
    }

    const TYPE_ARRAYS = {
      float32: Float32Array,
      uint8: Uint8Array,
      uint16: Uint16Array,
      uint32: Uint32Array,
      int32: Int32Array,
    };

    function decodePackedArray(value) {
      if (!value || value.encoding !== "base64" || typeof value.data !== "string") {
        return null;
      }
      const TypeCtor = TYPE_ARRAYS[value.dtype];
      if (!TypeCtor) {
        console.warn("Unsupported packed array dtype:", value.dtype);
        return null;
      }
      const binary = atob(value.data);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i) & 0xff;
      }
      const bytesPerElement = TypeCtor.BYTES_PER_ELEMENT;
      const expectedLength = Number.isInteger(value.length) ? value.length : Math.floor(bytes.length / bytesPerElement);
      const expectedBytes = expectedLength * bytesPerElement;
      if (expectedBytes > bytes.byteLength || expectedBytes % bytesPerElement !== 0) {
        console.warn("Packed array size mismatch:", value);
        return null;
      }
      return new TypeCtor(bytes.buffer, bytes.byteOffset, expectedLength);
    }

    function unpackArray(value) {
      if (value == null) return null;
      if (Array.isArray(value) || ArrayBuffer.isView(value)) {
        return value;
      }
      return decodePackedArray(value);
    }

    function toFloat32Array(value) {
      const unpacked = unpackArray(value);
      if (unpacked == null) return null;
      if (unpacked instanceof Float32Array) return unpacked;
      if (Array.isArray(unpacked) || ArrayBuffer.isView(unpacked)) {
        return new Float32Array(unpacked);
      }
      return null;
    }

    function toUint8Array(value) {
      const unpacked = unpackArray(value);
      if (unpacked == null) return null;
      if (unpacked instanceof Uint8Array || unpacked instanceof Uint8ClampedArray) {
        return unpacked;
      }
      if (Array.isArray(unpacked) || ArrayBuffer.isView(unpacked)) {
        return new Uint8Array(unpacked);
      }
      return null;
    }

    function toIndexArray(value) {
      const unpacked = unpackArray(value);
      if (unpacked == null) return null;
      if (
        unpacked instanceof Uint16Array ||
        unpacked instanceof Uint32Array ||
        unpacked instanceof Int32Array
      ) {
        return unpacked;
      }
      if (!Array.isArray(unpacked) && !ArrayBuffer.isView(unpacked)) {
        return null;
      }
      const arrayValues = Array.from(unpacked);
      if (!arrayValues.length) return null;
      let maxValue = 0;
      for (const v of arrayValues) {
        if (v > maxValue) maxValue = v;
      }
      return maxValue < 65536 ? new Uint16Array(arrayValues) : new Uint32Array(arrayValues);
    }

    function safeBufferAttribute(array, itemSize, label) {
      if (!array || typeof array.length !== "number" || array.length === 0) {
        console.warn("Skipping invalid attribute:", label, array);
        return null;
      }
      try {
        return new THREE.BufferAttribute(array, itemSize);
      } catch (error) {
        console.warn("Failed to build attribute:", label, error, array);
        return null;
      }
    }

    function rgbArrayToAttribute(values, itemSize = 3) {
      const array = toFloat32Array(values);
      if (!array || !array.length) return null;
      return safeBufferAttribute(array, itemSize, "color");
    }

    function buildGeometry(object) {
      const geometry = new THREE.BufferGeometry();
      const positions = toFloat32Array(object.positions);
      if (!positions || !positions.length) {
        return null;
      }
      const positionAttr = safeBufferAttribute(positions, 3, `${object.name || object.kind}:position`);
      if (!positionAttr) {
        return null;
      }
      geometry.setAttribute("position", positionAttr);
      const normals = toFloat32Array(object.normals);
      const hasNormals = normals && normals.length === positions.length;
      if (hasNormals) {
        const normalAttr = safeBufferAttribute(normals, 3, `${object.name || object.kind}:normal`);
        if (normalAttr) {
          geometry.setAttribute("normal", normalAttr);
        }
      }
      const uvs = toFloat32Array(object.uvs);
      if (uvs && uvs.length) {
        const uvAttr = safeBufferAttribute(uvs, 2, `${object.name || object.kind}:uv`);
        if (uvAttr) {
          geometry.setAttribute("uv", uvAttr);
        }
      }
      const vertexColors = unpackArray(object.vertex_colors);
      if (vertexColors && vertexColors.length) {
        const colorAttr = rgbArrayToAttribute(vertexColors);
        if (colorAttr) {
          geometry.setAttribute("color", colorAttr);
        }
      }
      const indices = toIndexArray(object.indices);
      if (indices && indices.length) {
        const indexAttr = safeBufferAttribute(indices, 1, `${object.name || object.kind}:index`);
        if (indexAttr) {
          geometry.setIndex(indexAttr);
        }
      }
      if (object.kind === "mesh" && !geometry.getAttribute("normal")) {
        geometry.computeVertexNormals();
      }
      geometry.computeBoundingSphere();
      return geometry;
    }

    function buildTexture(textureData) {
      if (!textureData || !textureData.data) {
        return null;
      }
      const src = toUint8Array(textureData.data);
      if (!src || !src.length) {
        return null;
      }
      const srcClamped = src instanceof Uint8ClampedArray ? src : new Uint8ClampedArray(src);
      const rgba = new Uint8ClampedArray(textureData.width * textureData.height * 4);
      if (textureData.channels === 4) {
        rgba.set(srcClamped);
      } else {
        for (let i = 0, j = 0; i < srcClamped.length; i += 3, j += 4) {
          rgba[j] = srcClamped[i];
          rgba[j + 1] = srcClamped[i + 1];
          rgba[j + 2] = srcClamped[i + 2];
          rgba[j + 3] = 255;
        }
      }
      const canvas = document.createElement("canvas");
      canvas.width = textureData.width;
      canvas.height = textureData.height;
      const ctx = canvas.getContext("2d");
      const imageData = new ImageData(rgba, textureData.width, textureData.height);
      ctx.putImageData(imageData, 0, 0);
      const texture = new THREE.CanvasTexture(canvas);
      texture.colorSpace = THREE.SRGBColorSpace;
      texture.flipY = true;
      texture.generateMipmaps = false;
      texture.wrapS = textureData.repeat ? THREE.RepeatWrapping : THREE.ClampToEdgeWrapping;
      texture.wrapT = textureData.repeat ? THREE.RepeatWrapping : THREE.ClampToEdgeWrapping;
      texture.magFilter = textureData.interpolate ? THREE.LinearFilter : THREE.NearestFilter;
      texture.minFilter = textureData.interpolate ? THREE.LinearFilter : THREE.NearestFilter;
      texture.needsUpdate = true;
      return texture;
    }

    function buildEdgeLines(object) {
      const edgeSegments = toFloat32Array(object.edge_segments);
      if (!edgeSegments || !edgeSegments.length) {
        return null;
      }
      const edgeGeometry = new THREE.BufferGeometry();
      const edgeAttr = safeBufferAttribute(edgeSegments, 3, `${object.name || object.kind}:edges`);
      if (!edgeAttr) {
        return null;
      }
      edgeGeometry.setAttribute(
        "position",
        edgeAttr
      );
      const edgeMaterial = new THREE.LineBasicMaterial({
        color: object.edge_color || object.color || "#d9dde3",
        transparent: object.opacity < 0.999,
        opacity: object.opacity,
      });
      return new THREE.LineSegments(edgeGeometry, edgeMaterial);
    }

    function makeLabel(object) {
      const el = document.createElement("div");
      el.className = "label-2d";
      el.textContent = object.text;
      el.style.left = `${object.position[0] * 100}%`;
      el.style.top = `${(1 - object.position[1]) * 100}%`;
      el.style.color = object.color || "#ffffff";
      el.style.fontSize = `${Math.max(11, object.size * 14)}px`;
      if (object.frame) {
        el.style.border = "1px solid rgba(255,255,255,0.25)";
      }
      if (object.background) {
        el.style.background = object.background;
      }
      container.appendChild(el);
    }

    const bounds = new THREE.Box3();
    let hasRenderableObjects = false;

    for (const object of payload.objects) {
      if (object.kind === "text2d") {
        makeLabel(object);
        continue;
      }

      if (object.kind === "mesh") {
        const geometry = buildGeometry(object);
        if (!geometry) {
          console.warn("Skipping mesh with invalid geometry:", object.name || object.kind);
          continue;
        }
        const texture = buildTexture(object.texture);
        const baseColor = new THREE.Color(texture ? "#ffffff" : (object.color || "#d9dde3"));
        const exportedSpecular = typeof object.specular === "number" ? object.specular : 0;
        const useSpecularFallback =
          Boolean(object.lighting) &&
          !Boolean(object.flat_shading) &&
          exportedSpecular <= 1e-6;
        const ambientStrength =
          !object.lighting ? 1.0 : ((object.ambient || 0) * (tuning.ambient_scale ?? 0.25));
        const emissive = baseColor.clone().multiplyScalar(ambientStrength);
        const specularStrength = useSpecularFallback
          ? (tuning.fallback_specular_strength ?? 0.35)
          : (exportedSpecular * (tuning.specular_scale ?? 0.45));
        const specularColor = new THREE.Color(object.specular_color || "#111111");
        if (useSpecularFallback) {
          // VTK's default shaded look still reads slightly glossy even when the
          // raw property exports as specular=0. Add a small highlight so smooth
          // surfaces like the bunny do not become unnaturally matte in Three.js.
          specularColor.lerp(new THREE.Color("#ffffff"), 0.5);
        }
        const shininess =
          exportedSpecular > 1e-6
            ? Math.max(1, object.specular_power || 1)
            : (useSpecularFallback
              ? Math.max(1, tuning.fallback_shininess ?? 28)
              : Math.max(1, object.specular_power || 1));
        const material = new THREE.MeshPhongMaterial({
          color: baseColor,
          side: THREE.DoubleSide,
          transparent: object.opacity < 0.999,
          opacity: object.opacity,
          wireframe: false,
          flatShading: Boolean(object.flat_shading),
          vertexColors: Boolean(object.vertex_colors && object.vertex_colors.length),
          map: texture,
          emissive,
          specular: specularColor.multiplyScalar(specularStrength),
          shininess,
          polygonOffset: Boolean(object.edge_visibility),
          polygonOffsetFactor: 1,
          polygonOffsetUnits: 1,
        });
        material.toneMapped = false;
        if (!object.lighting) {
          material.emissive.copy(baseColor);
        } else if (
          !Boolean(tuning.preserve_base_color) &&
          typeof object.diffuse === "number" &&
          object.diffuse < 0.999
        ) {
          material.color.multiplyScalar(object.diffuse);
        }
        const mesh = new THREE.Mesh(geometry, material);
        const group = new THREE.Group();
        if (!object.wireframe) {
          group.add(mesh);
        }
        const edges = buildEdgeLines(object);
        if (edges && (object.wireframe || object.edge_visibility)) {
          group.add(edges);
        }
        scene.add(group);
        bounds.expandByObject(group);
        hasRenderableObjects = true;
        continue;
      }

      if (object.kind === "points") {
        const geometry = buildGeometry(object);
        if (!geometry) {
          console.warn("Skipping points with invalid geometry:", object.name || object.kind);
          continue;
        }
        const material = new THREE.PointsMaterial({
          color: object.color || "#d9dde3",
          size: object.point_size || 4,
          transparent: object.opacity < 0.999,
          opacity: object.opacity,
          vertexColors: Boolean(object.vertex_colors && object.vertex_colors.length),
          sizeAttenuation: true,
        });
        const points = new THREE.Points(geometry, material);
        applyMatrix(points, object.matrix);
        scene.add(points);
        bounds.expandByObject(points);
        hasRenderableObjects = true;
        continue;
      }

      if (object.kind === "lines") {
        const material = new THREE.LineBasicMaterial({
          color: object.color || "#d9dde3",
          transparent: object.opacity < 0.999,
          opacity: object.opacity,
          vertexColors: Boolean(object.vertex_colors && object.vertex_colors.length),
        });
        const group = new THREE.Group();
        for (const polyline of object.polylines) {
          if (!polyline || polyline.length < 2) continue;
          const lineGeometry = new THREE.BufferGeometry();
          const linePositions = toFloat32Array(polyline);
          const lineAttr = safeBufferAttribute(linePositions, 3, `${object.name || object.kind}:polyline`);
          if (!lineAttr) {
            continue;
          }
          lineGeometry.setAttribute("position", lineAttr);
          const line = new THREE.Line(lineGeometry, material);
          group.add(line);
        }
        applyMatrix(group, object.matrix);
        scene.add(group);
        bounds.expandByObject(group);
        hasRenderableObjects = true;
      }
    }

    if (payload.unsupported.length) {
      unsupportedEl.textContent =
        "Not rendered in this v1 exporter: " +
        payload.unsupported.map((item) => item.label).join(", ");
    }

    if (!hasRenderableObjects) {
      unsupportedEl.textContent =
        (unsupportedEl.textContent ? unsupportedEl.textContent + "\\n" : "") +
        "This scene did not contain any supported Three.js-exportable objects.";
    }

    function updateCamera() {
      const width = window.innerWidth;
      const height = Math.max(window.innerHeight, 1);
      const newAspect = width / height;
      if (camera.isPerspectiveCamera) {
        camera.aspect = newAspect;
      } else {
        const scale = payload.camera.parallel_scale || 1;
        camera.left = -scale * newAspect;
        camera.right = scale * newAspect;
        camera.top = scale;
        camera.bottom = -scale;
      }
      camera.updateProjectionMatrix();
      renderer.setSize(width, height);
    }

    function render() {
      renderer.render(scene, camera);
    }

    window.addEventListener("resize", () => {
      updateCamera();
      render();
    });
    controls.addEventListener("change", render);
    updateCamera();
    render();
  </script>
</body>
</html>
"""


def _pack_numeric_array(value, dtype, min_values=64):
    """Pack large numeric arrays as base64-encoded typed buffers."""
    if value is None:
        return []
    arr = np.asarray(value, dtype=dtype)
    if arr.size == 0:
        return []
    flat = np.ascontiguousarray(arr.reshape(-1))
    if flat.size < min_values:
        return flat.tolist()
    return {
        "encoding": "base64",
        "dtype": np.dtype(dtype).name,
        "length": int(flat.size),
        "data": base64.b64encode(flat.tobytes()).decode("ascii"),
    }


def _flatten_numeric_array(value) -> list[float]:
    """Flatten an array-like value to a 1D Python list."""
    if value is None:
        return []
    arr = np.asarray(value)
    if arr.size == 0:
        return []
    return arr.reshape(-1).tolist()


def _triangulate_flat_cells(flat_cells) -> list[int]:
    """Convert VTK-style polygon connectivity into triangle indices."""
    if flat_cells is None:
        return []
    cells = np.asarray(flat_cells, dtype=int).ravel()
    triangles = []
    i = 0
    ncells = len(cells)
    while i < ncells:
        nids = int(cells[i])
        ids = cells[i + 1 : i + 1 + nids]
        if nids >= 3:
            root = int(ids[0])
            for j in range(1, nids - 1):
                triangles.extend([root, int(ids[j]), int(ids[j + 1])])
        i += nids + 1
    return triangles


def _polygon_edge_segments(flat_cells, points) -> list[float]:
    """Build unique polygon edge segments without triangulation diagonals."""
    if flat_cells is None:
        return []
    cells = np.asarray(flat_cells, dtype=int).ravel()
    pts = np.asarray(points, dtype=float)
    segments = []
    seen = set()
    i = 0
    ncells = len(cells)
    while i < ncells:
        nids = int(cells[i])
        ids = cells[i + 1 : i + 1 + nids]
        if nids >= 2:
            for j in range(nids):
                a = int(ids[j])
                b = int(ids[(j + 1) % nids])
                key = (a, b) if a < b else (b, a)
                if key in seen:
                    continue
                seen.add(key)
                segments.extend(pts[[a, b]].reshape(-1).tolist())
        i += nids + 1
    return segments


def _map_scalars_to_colors(values, lut, value_range) -> list[float]:
    """Map scalar values to vertex colors using a lookup table."""
    if values is None or lut is None:
        return []

    arr = np.asarray(values, dtype=float).ravel()
    table = np.asarray(lut, dtype=float)
    if arr.size == 0 or table.size == 0:
        return []

    if value_range is None:
        lo = float(np.nanmin(arr))
        hi = float(np.nanmax(arr))
    else:
        lo, hi = map(float, value_range)

    if hi <= lo:
        idx = np.zeros(arr.shape[0], dtype=int)
    else:
        scaled = np.clip((arr - lo) / (hi - lo), 0.0, 1.0)
        idx = np.rint(scaled * (len(table) - 1)).astype(int)
    return table[idx, :3].astype(float).reshape(-1).tolist()


def _extract_vertex_colors(obj: dict, npoints: int) -> list[float]:
    """Extract point-based colors when available."""
    pointdata = obj.get("pointdata") or {}
    candidate_names = []
    array_name = obj.get("array_name_to_color_by")
    if array_name:
        candidate_names.append(array_name)
    candidate_names.extend(["RGBA", "VertexColors", "Colors", "Scalars"])

    for name in candidate_names:
        if name not in pointdata:
            continue
        arr = np.asarray(pointdata[name])
        if arr.ndim == 2 and arr.shape[0] == npoints and arr.shape[1] in (3, 4):
            cols = arr[:, :3].astype(float)
            if cols.size and np.nanmax(cols) > 1.0:
                cols /= 255.0
            return cols.reshape(-1).tolist()
        if (
            arr.ndim == 1
            and arr.shape[0] == npoints
            and obj.get("scalar_visibility")
            and obj.get("LUT") is not None
        ):
            return _map_scalars_to_colors(arr, obj.get("LUT"), obj.get("scalar_range"))
    return []


def _extract_texture_payload(
    obj: dict, pack_arrays=True
) -> tuple[dict | None, dict | None]:
    """Extract mesh texture data when present and supported."""
    texture_array = obj.get("texture_array")
    if texture_array is None:
        return None, None

    uvs = (
        np.asarray(obj.get("texture_coordinates"))
        if obj.get("texture_coordinates") is not None
        else None
    )
    if uvs is None or uvs.size == 0:
        label = obj.get("name") or obj.get("filename") or "Mesh"
        return None, {"label": f"{label} (texture without UVs)"}

    image = np.asarray(texture_array)
    if image.ndim == 2:
        image = np.repeat(image[:, :, None], 3, axis=2)
    if image.ndim != 3 or image.shape[2] not in (3, 4):
        label = obj.get("name") or obj.get("filename") or "Mesh"
        return None, {"label": f"{label} (unsupported texture format)"}

    if image.dtype != np.uint8:
        if np.issubdtype(image.dtype, np.floating):
            image = np.clip(image, 0.0, 1.0) * 255.0
        image = image.astype(np.uint8)

    return (
        {
            "width": int(image.shape[1]),
            "height": int(image.shape[0]),
            "channels": int(image.shape[2]),
            "data": _pack_numeric_array(image, np.uint8, min_values=256)
            if pack_arrays
            else image.reshape(-1).tolist(),
            "repeat": bool(obj.get("texture_repeat")),
            "interpolate": bool(obj.get("texture_interpolate")),
        },
        None,
    )


def _scene_object_to_threejs(
    obj: dict, pack_arrays=True
) -> tuple[dict | None, dict | None]:
    """Convert a serialized scene object to a Three.js-friendly payload."""
    from .scene import _color_to_hex

    otype = obj.get("type", "unknown")
    label = obj.get("name") or obj.get("filename") or otype

    if otype == "Text2D":
        bgcol = obj.get("bgcol")
        alpha_value = obj.get("alpha")
        alpha = 0.0 if alpha_value is None else float(alpha_value)
        background = None
        if bgcol is not None and alpha > 0:
            r, g, b = colors.get_color(bgcol)
            background = "rgba({:.0f}, {:.0f}, {:.0f}, {:.3f})".format(
                r * 255, g * 255, b * 255, alpha
            )
        return (
            {
                "kind": "text2d",
                "name": label,
                "text": obj.get("text", ""),
                "position": [float(obj["position"][0]), float(obj["position"][1])],
                "color": _color_to_hex(obj.get("color")),
                "size": float(1.0 if obj.get("size") is None else obj.get("size")),
                "frame": bool(obj.get("frame")),
                "background": background,
            },
            None,
        )

    if otype != "Mesh":
        return None, {"label": f"{label} ({otype})"}

    points = np.asarray(obj.get("points"), dtype=float)
    if points.size == 0:
        return None, None

    base = {
        "name": label,
        "color": _color_to_hex(obj.get("color")) or "#d9dde3",
        "opacity": float(1.0 if obj.get("alpha") is None else obj.get("alpha")),
        "flat_shading": int(obj.get("shading", 1)) == 0,
        "wireframe": int(obj.get("representation", 0)) == 1,
        "edge_visibility": bool(obj.get("edge_visibility")),
        "edge_color": _color_to_hex(obj.get("linecolor"))
        or _color_to_hex(obj.get("color"))
        or "#d9dde3",
        "line_width": float(
            1.0 if obj.get("linewidth") is None else obj.get("linewidth")
        ),
        "ambient": float(0.0 if obj.get("ambient") is None else obj.get("ambient")),
        "diffuse": float(1.0 if obj.get("diffuse") is None else obj.get("diffuse")),
        "specular": float(0.0 if obj.get("specular") is None else obj.get("specular")),
        "specular_power": float(
            1.0 if obj.get("specularpower") is None else obj.get("specularpower")
        ),
        "specular_color": _color_to_hex(obj.get("specularcolor")) or "#111111",
        "lighting": bool(
            True if obj.get("lighting_is_on") is None else obj.get("lighting_is_on")
        ),
        "back_color": _color_to_hex(obj.get("backcolor")),
    }
    vertex_colors = _extract_vertex_colors(obj, len(points))
    texture_payload, texture_warning = _extract_texture_payload(
        obj, pack_arrays=pack_arrays
    )

    cells = obj.get("cells")
    if cells is not None and len(np.asarray(cells).ravel()) > 0:
        return (
            {
                **base,
                "kind": "mesh",
                "positions": _pack_numeric_array(points, np.float32)
                if pack_arrays
                else points.reshape(-1).tolist(),
                "indices": (
                    _pack_numeric_array(
                        _triangulate_flat_cells(cells),
                        np.uint16 if len(points) < 65536 else np.uint32,
                    )
                    if pack_arrays
                    else _triangulate_flat_cells(cells)
                ),
                "normals": (
                    _pack_numeric_array(obj.get("point_normals"), np.float32)
                    if pack_arrays
                    else _flatten_numeric_array(obj.get("point_normals"))
                ),
                "uvs": (
                    _pack_numeric_array(obj.get("texture_coordinates"), np.float32)
                    if pack_arrays
                    else _flatten_numeric_array(obj.get("texture_coordinates"))
                ),
                "vertex_colors": (
                    _pack_numeric_array(vertex_colors, np.float32)
                    if pack_arrays
                    else vertex_colors
                ),
                "texture": texture_payload,
                "edge_segments": (
                    _pack_numeric_array(
                        _polygon_edge_segments(cells, points), np.float32
                    )
                    if pack_arrays
                    else _polygon_edge_segments(cells, points)
                ),
            },
            texture_warning,
        )

    lines = obj.get("lines")
    if lines is not None and len(lines):
        polylines = []
        for line in lines:
            ids = np.asarray(line, dtype=int).ravel()
            if ids.size < 2:
                continue
            polylines.append(points[ids].reshape(-1).tolist())
        return (
            {
                **base,
                "kind": "lines",
                "polylines": polylines,
                "vertex_colors": _pack_numeric_array(vertex_colors, np.float32)
                if pack_arrays
                else vertex_colors,
            },
            None,
        )

    return (
        {
            **base,
            "kind": "points",
            "positions": _pack_numeric_array(points, np.float32)
            if pack_arrays
            else points.reshape(-1).tolist(),
            "point_size": max(
                float(4.0 if obj.get("pointsize") is None else obj.get("pointsize")),
                1.0,
            ),
            "vertex_colors": _pack_numeric_array(vertex_colors, np.float32)
            if pack_arrays
            else vertex_colors,
        },
        None,
    )


def _normalize_threejs_options(options: dict | None = None) -> dict:
    """Validate and normalize Three.js export tuning options."""
    defaults = {
        "headlight_intensity": 1.0,
        "ambient_scale": 0.25,
        "specular_scale": 0.45,
        "fallback_specular_strength": 0.35,
        "fallback_shininess": 28.0,
        "preserve_base_color": False,
        "pack_arrays": True,
    }
    if not options:
        return defaults

    normalized = dict(defaults)
    for key, value in options.items():
        if key not in normalized:
            continue
        if key in ("preserve_base_color", "pack_arrays"):
            normalized[key] = bool(value)
        else:
            try:
                normalized[key] = float(value)
            except (TypeError, ValueError):
                pass

    normalized["headlight_intensity"] = max(normalized["headlight_intensity"], 0.0)
    normalized["ambient_scale"] = max(normalized["ambient_scale"], 0.0)
    normalized["specular_scale"] = max(normalized["specular_scale"], 0.0)
    normalized["fallback_specular_strength"] = max(
        normalized["fallback_specular_strength"], 0.0
    )
    normalized["fallback_shininess"] = max(normalized["fallback_shininess"], 1.0)
    return normalized


def _scene_to_threejs_payload(plt, backend_options: dict | None = None) -> dict:
    """Build a Three.js-specific scene payload from the current Plotter."""
    from .scene import _color_to_hex, _json_compatible, _plotter_to_scene_dict

    scene = _plotter_to_scene_dict(plt)
    has_real_axes = any(
        isinstance(obj.get("metadata"), dict)
        and obj["metadata"].get("assembly") == "Axes"
        for obj in scene.get("objects", [])
    )
    payload = {
        "title": scene.get("title") or "vedo scene",
        "camera": {
            "position": _json_compatible(scene["camera"]["pos"]),
            "focal_point": _json_compatible(scene["camera"]["focal_point"]),
            "viewup": _json_compatible(scene["camera"]["viewup"]),
            "parallel_projection": bool(scene.get("use_parallel_projection")),
            "parallel_scale": float(
                1.0
                if scene["camera"].get("parallel_scale") is None
                else scene["camera"].get("parallel_scale")
            ),
        },
        "background": {
            "primary": _color_to_hex(scene.get("backgrcol")),
            "secondary": _color_to_hex(scene.get("backgrcol2")),
        },
        "threejs": _normalize_threejs_options(backend_options),
        "helpers": {
            "show_axes": bool(scene.get("axes")) and not has_real_axes,
            "axes_size": 1.0,
            "show_grid": scene.get("axes") in (1, 11) and not has_real_axes,
            "grid_size": 10.0,
            "grid_divisions": 10,
        },
        "objects": [],
        "unsupported": [],
    }
    pack_arrays = bool(payload["threejs"].get("pack_arrays", True))

    for obj in scene.get("objects", []):
        three_obj, unsupported = _scene_object_to_threejs(obj, pack_arrays=pack_arrays)
        if three_obj is not None:
            payload["objects"].append(three_obj)
        if unsupported is not None:
            payload["unsupported"].append(unsupported)
    return payload


def _export_threejs(
    plt, fileoutput="scene.html", backend_options: dict | None = None
) -> None:
    """Export the current scene as a standalone Three.js HTML document."""
    from .scene import _json_compatible

    payload = _scene_to_threejs_payload(plt, backend_options=backend_options)
    primary = payload["background"]["primary"] or "#1f2937"
    secondary = payload["background"]["secondary"]
    if secondary:
        background = f"linear-gradient(180deg, {primary} 0%, {secondary} 100%)"
    else:
        background = primary

    scene_data = json.dumps(_json_compatible(payload), separators=(",", ":"))
    scene_data = scene_data.replace("</script>", "<\\/script>")
    html = _threejs_html_template.replace("~title", payload["title"])
    html = html.replace("~background", background)
    html = html.replace("~scene_data", scene_data)
    with open(fileoutput, "w", encoding="UTF-8") as outF:
        outF.write(html)
