site_name: vedo
site_description: Documentation for vedo

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: false
      pygments_lang_class: true
  - pymdownx.superfences

extra_css:
  - assets/docs-overrides.css

exclude_docs: |
  logos/*.py

theme:
  name: swan

plugins:
  - material/search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            filters:
              - "!^_.*$"
            docstring_options:
              warn_unknown_params: false
              warn_missing_types: false

nav:
  - Home: index.md
  - API:
      - Overview: api/index.md
      - addons: api/addons.md
      - applications: api/applications.md
      - assembly: api/assembly.md
      - backends: api/backends.md
      - chemistry: api/chemistry.md
      - colors: api/colors.md
      - core: api/core.md
      - file_io: api/file_io.md
      - grids: api/grids.md
      - mesh: api/mesh.md
      - plotter: api/plotter.md
      - pointcloud: api/pointcloud.md
      - pyplot: api/pyplot.md
      - settings: api/settings.md
      - shapes: api/shapes.md
      - transformations: api/transformations.md
      - utils: api/utils.md
      - visual: api/visual.md
      - volume: api/volume.md
